### PR TITLE
[eslint-plugin] auto fix peer-deps-in-dev-deps

### LINKED ISSUE #97: peerDepsInDevDeps 개선
https://github.com/NaverPayDev/code-style/blob/main/packages/eslint-plugin/lib/rules/peer-deps-in-dev-deps.js

- 정확한 에러 위치 잡아주기
- fixable하게 바꿀 수 있는 아이디어

### PR DESCRIPTION
**Pull request by yongholeeme**
## Related Issue

close #97 

## Describe your changes

https://github.com/user-attachments/assets/e62ff1d5-93e1-4d33-8b6d-5102b1e16405

https://github.com/user-attachments/assets/daa05872-d402-4cdf-8c30-f3b5d5885fcf

https://github.com/user-attachments/assets/3b5e09f4-845b-4c46-b9ff-d014736fa16b

https://github.com/user-attachments/assets/de38dc6e-39e2-411e-a369-00d11e2584fd

### CODE REVIEW

**Review by 2-one-week — DISMISSED** [review]
확인했습니다!

File: packages/eslint-plugin/lib/rules/peer-deps-in-dev-deps.js [hunk 1]
```diff
@@ -46,13 +46,37 @@ export default {
...
+                for (const [depName, depVersion] of Object.entries(peerDeps)) {
                     if (!Object.prototype.hasOwnProperty.call(devDeps, depName)) {
                         context.report({
                             node,
                             messageId: 'missingInDevDeps',
                             data: {packageName: depName},
                             loc: devDepsNode?.loc || peerDepsNode?.loc,
+                            fix(fixer) {
+                                const s = ' '.repeat(getIndentationLength(sourceCode.getText()))
+                                const ss = s.repeat(2)
```
Comment (yceffort-naver) [inline packages/eslint-plugin/lib/rules/peer-deps-in-dev-deps.js:58]: ㅋㅋㅋㅋ 스페이스 군요 ㅋㅋ

**Review by yceffort-naver — DISMISSED** [review]
감사합니다!

**Review by byhhh2 — APPROVED** [review]
ㄷㄷ
LGTM! 수고많으셨습니다~!
